"""
Report generation (Section 7.16). Produces PDF, HTML, and CSV, and logs
every generation to the Report table so history is a first-class list
rather than an afterthought.
"""
import csv
import io
import os
from datetime import datetime

from jinja2 import Template
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from ..config import settings
from ..models import Case, Report

# NOTE: PDF generation uses reportlab (pure Python, no native system
# libraries required) rather than WeasyPrint. WeasyPrint depends on
# Pango/Cairo/GDK-Pixbuf at the OS level, which Render's default Python
# buildpack does not install — that would break PDF export at build or
# runtime on a free-tier deploy. reportlab ships as a normal pip wheel.

HTML_TEMPLATE = Template("""
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; margin: 40px; }
  h1 { color: #4338ca; border-bottom: 2px solid #4338ca; padding-bottom: 8px; }
  .badge { display:inline-block; padding:4px 10px; border-radius:12px; font-weight:600; font-size:12px; }
  .critical { background:#fee2e2; color:#b91c1c; }
  .high { background:#ffedd5; color:#c2410c; }
  .medium { background:#fef9c3; color:#a16207; }
  .low { background:#dcfce7; color:#166534; }
  table { width:100%; border-collapse: collapse; margin: 16px 0; }
  th, td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; font-size: 13px; }
  th { background: #f3f4f6; }
  .section { margin-top: 28px; }
</style>
</head>
<body>
  <h1>CaseIntel Investigation Report — {{ case.case_number }}</h1>
  <p><strong>Label:</strong> {{ case.label or "—" }} &nbsp; | &nbsp;
     <strong>Verdict:</strong> {{ case.verdict.value }} &nbsp; | &nbsp;
     <strong>Risk:</strong> <span class="badge {{ case.risk_level.value }}">{{ case.risk_score }} — {{ case.risk_level.value|upper }}</span></p>
  <p><strong>SHA256:</strong> {{ case.sha256 }}</p>
  <p><strong>Examiner:</strong> {{ case.examiner or "—" }} &nbsp; | &nbsp;
     <strong>Uploaded:</strong> {{ case.upload_timestamp }}</p>

  <div class="section">
    <h2>Executive Summary</h2>
    <p>{{ case.executive_summary or "Not yet generated." }}</p>
    <h3>Key Findings</h3>
    <ul>{% for kf in case.key_findings %}<li>{{ kf }}</li>{% endfor %}</ul>
    <p><strong>Recommendation:</strong> {{ case.recommendation or "—" }} &nbsp;
       <strong>Confidence:</strong> {{ case.confidence or "—" }}%</p>
  </div>

  <div class="section">
    <h2>Risk Score Breakdown</h2>
    <table>
      <tr><th>Rule</th><th>Contribution</th><th>Counted</th></tr>
      {% for rule, info in case.risk_contributions.items() %}
      <tr><td>{{ rule }}</td><td>+{{ info.weight }}</td><td>{{ "Yes" if info.counted else "Redundant evidence" }}</td></tr>
      {% endfor %}
    </table>
  </div>

  <div class="section">
    <h2>MITRE ATT&CK Mapping</h2>
    <table>
      <tr><th>Technique ID</th><th>Name</th><th>Confidence</th></tr>
      {% for t in case.mitre_techniques %}
      <tr><td>{{ t.id }}</td><td>{{ t.name }}</td><td>{{ t.confidence }}%</td></tr>
      {% endfor %}
    </table>
  </div>

  <div class="section">
    <h2>Full Narrative</h2>
    <p>{{ case.narrative or "—" }}</p>
  </div>

  <p style="margin-top:40px; font-size:11px; color:#6b7280;">
    Correlation is similarity, not attribution. This report never states "same actor" or "confirmed related."
    Generated by CaseIntel v3.0.
  </p>
</body>
</html>
""")


def generate_html(case: Case) -> str:
    return HTML_TEMPLATE.render(case=case)


RISK_COLORS = {
    "critical": colors.HexColor("#b91c1c"),
    "high": colors.HexColor("#c2410c"),
    "medium": colors.HexColor("#a16207"),
    "low": colors.HexColor("#166534"),
}


def generate_pdf_bytes(case: Case) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], textColor=colors.HexColor("#4338ca"))
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], spaceBefore=14)
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=8, textColor=colors.grey)

    risk_level = case.risk_level.value if hasattr(case.risk_level, "value") else str(case.risk_level)
    verdict = case.verdict.value if hasattr(case.verdict, "value") else str(case.verdict)

    story = [
        Paragraph(f"CaseIntel Investigation Report — {case.case_number}", h1),
        Paragraph(
            f"Label: {case.label or '—'} &nbsp;|&nbsp; Verdict: {verdict} &nbsp;|&nbsp; "
            f'Risk: <font color="#{RISK_COLORS.get(risk_level, colors.black).hexval()[2:]}">'
            f"{case.risk_score} — {risk_level.upper()}</font>",
            body,
        ),
        Paragraph(f"SHA256: {case.sha256}", small),
        Paragraph(f"Examiner: {case.examiner or '—'} &nbsp;|&nbsp; Uploaded: {case.upload_timestamp}", small),
        Spacer(1, 12),

        Paragraph("Executive Summary", h2),
        Paragraph(case.executive_summary or "Not yet generated.", body),
        Paragraph("Key Findings", styles["Heading3"]),
    ]
    for kf in (case.key_findings or []):
        story.append(Paragraph(f"• {kf}", body))
    story.append(Paragraph(
        f"Recommendation: {case.recommendation or '—'} &nbsp; Confidence: {case.confidence or '—'}%", body
    ))

    story.append(Paragraph("Risk Score Breakdown", h2))
    risk_rows = [["Rule", "Contribution", "Counted"]]
    for rule, info in (case.risk_contributions or {}).items():
        risk_rows.append([rule, f"+{info.get('weight')}", "Yes" if info.get("counted") else "Redundant evidence"])
    if len(risk_rows) > 1:
        t = Table(risk_rows, colWidths=[2.5 * inch, 1.3 * inch, 2 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(t)

    story.append(Paragraph("MITRE ATT&CK Mapping", h2))
    mitre_rows = [["Technique ID", "Name", "Confidence"]]
    for t in (case.mitre_techniques or []):
        mitre_rows.append([t.get("id", ""), t.get("name", ""), f"{t.get('confidence', '')}%"])
    if len(mitre_rows) > 1:
        mt = Table(mitre_rows, colWidths=[1.3 * inch, 3 * inch, 1.3 * inch])
        mt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(mt)

    story.append(Paragraph("Full Narrative", h2))
    story.append(Paragraph(case.narrative or "—", body))
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        'Correlation is similarity, not attribution. This report never states "same actor" or '
        '"confirmed related." Generated by CaseIntel v3.0.', small
    ))

    doc.build(story)
    return buf.getvalue()


def generate_csv_bytes(case: Case) -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Field", "Value"])
    writer.writerow(["Case Number", case.case_number])
    writer.writerow(["Label", case.label or ""])
    writer.writerow(["Verdict", case.verdict.value])
    writer.writerow(["Risk Score", case.risk_score])
    writer.writerow(["Risk Level", case.risk_level.value])
    writer.writerow(["SHA256", case.sha256])
    writer.writerow(["Examiner", case.examiner or ""])
    writer.writerow(["Upload Timestamp", case.upload_timestamp])
    writer.writerow([])
    writer.writerow(["Rule", "Contribution", "Counted"])
    for rule, info in (case.risk_contributions or {}).items():
        writer.writerow([rule, info.get("weight"), info.get("counted")])
    return buf.getvalue().encode("utf-8")


def save_report(db, case: Case, fmt: str, generated_by: str = "system") -> Report:
    version = f"v{len(case.reports) + 1}"
    filename = f"{case.case_number}-{fmt}-{version}.{fmt}"
    path = os.path.join(settings.REPORTS_DIR, filename)

    if fmt == "pdf":
        with open(path, "wb") as f:
            f.write(generate_pdf_bytes(case))
    elif fmt == "html":
        with open(path, "w", encoding="utf-8") as f:
            f.write(generate_html(case))
    elif fmt == "csv":
        with open(path, "wb") as f:
            f.write(generate_csv_bytes(case))
    else:
        raise ValueError(f"Unsupported format: {fmt}")

    report = Report(
        case_id=case.id,
        file_name=filename,
        format=fmt,
        version=version,
        generated_by=generated_by,
        generated_at=datetime.utcnow(),
        storage_path=path,
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report
